version: "3"
services:
  db:
    image: postgres:latest
    container_name: zespolowy-postgres-db
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: BazaProjekt

  adminer:
    image: adminer
    container_name: zespolowy-adminer
    restart: always
    ports:
      - "2080:8080"
